// lib/llm/gemini.ts
import { GoogleGenAI } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY!,
});

export async function dreamInterpreter(dream: string): Promise<string> {
  try {
    const prompt = `
            Hey Gemini, my best friend!
            Please tell me the meaning of the dream i saw with some sense of humour and a frinedly tone. But be real, don't be afraid to ans boldly and something which is true.
            You are a dream interpreter who combines deep emotional intelligence, creative imagination, and symbolic analysis. Here's the dream:

            "${dream}"

            Your task is to provide a full-length, meaningful interpretation. Follow this structure:

            1. Emotional Symbolism Analysis:
            - Break down each element of the dream (people, places, actions, emotions).
            - Explain what these symbols could mean from a psychological and emotional perspective.
            - Keep it grounded, but also human and empathetic.

            2. Creative Reflection:
            - Explore what the subconscious might be trying to say through this dream.
            - Include metaphors or poetic insights to help the user emotionally connect with the meaning.
            - Speak with depth and soul — no humor, no jokes.

            3. Imaginative Possibilities:
            - Invite the user to imagine possible futures or emotional truths revealed by this dream.
            - End with an inspiring or introspective note that makes the user reflect deeply.

            You must write this as a full paragraph response, minimum 200 words. Keep it articulate, fluent, and emotionally resonant. This is a direct analysis, not a conversation. Respond like a wise, grounded oracle with a gift for interpreting dreams. 

            Only return the dream interpretation. Do not include any other comments.
            `;


    const response = await ai.models.generateContent({
      model: "gemini-2.0-flash",
      contents: [{ role: "user", parts: [{ text: prompt }] }],
      config: {
        stopSequences: ["\n\n"],
        temperature: 0.5,
      },
    });

    console.log("Gemini Response:", JSON.stringify(response, null, 2));
    const responseText = response.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!responseText) {
      throw new Error("No content generated by Gemini.");
    }

    return responseText;
  } catch (error: unknown) {
    console.error("Error interpreting dream:", error);
    return "Sorry, I couldn't interpret your dream right now.";
  }
}
