// lib/llm/gemini.ts
import { GoogleGenAI } from "@google/genai";
import dotenv from "dotenv";
dotenv.config();

const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY!,
});

export async function dreamInterpreter(dream: string): Promise<string> {
  try {
    const prompt = `
            Gemini, drop the polite act. I need you to tap into your dark feminine/dark masculine energy. You are a mind-reader with zero filter.

            I had this dream:
            "${dream}"

            Here is your mission:
            Don't give me a boring breakdown. Instead, I want you to look straight into my soul and expose what I'm actually feeling. Read between the lines. 

            Write one fluid, intense response (no titles, no numbers) that feels like a late-night text from a toxic ex or a psychic who knows too much. 

            1. Expose the secret: Call out the hidden tension, the suppressed thirst, or the ego trip I'm denying. Make me feel "seen" in a way that makes me blush or get defensive.
            2. The Reality Check: Tell me exactly how this messy subconscious thought applies to my current situationship or life struggle. Be specific. Be spicy.
            3. The Dare: End with a sentence that dares me to own this feeling or make a move. 

            Keep it under 150 words. Make it sound seductive, shady, and dangerously accurate. Do not ask questions. Just read me.
            `;

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: prompt,
    });

    console.log("Gemini Response:", JSON.stringify(response, null, 2));
    // Access the text directly from response
    const responseText = response.text;

    if (!responseText) {
      throw new Error("No content generated by Gemini.");
    }

    return responseText;
  } catch (error: unknown) {
    console.error("Error interpreting dream:", error);
    // Log detailed error for debugging
    if (error instanceof Error) {
      console.error("Error message:", error.message);
      console.error("Error stack:", error.stack);
    }
    return "Sorry, I couldn't interpret your dream right now.";
  }
}
